// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_mkoUS6lCtdghA0BoPOVxywcJv0H_tA',
    appId: '1:828363531961:web:53ca30bf4a163c8b9cdd68',
    messagingSenderId: '828363531961',
    projectId: 'mpl-lab-922a1',
    authDomain: 'mpl-lab-922a1.firebaseapp.com',
    storageBucket: 'mpl-lab-922a1.firebasestorage.app',
    measurementId: 'G-09Y7SVZFK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-PO2UyqAW20IRWJC5tJPr7n5-4HAQFI',
    appId: '1:828363531961:android:7fa38319bc23b6469cdd68',
    messagingSenderId: '828363531961',
    projectId: 'mpl-lab-922a1',
    storageBucket: 'mpl-lab-922a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8mIx4sxko-5xT32KJUq84BtUHdi-k6s',
    appId: '1:828363531961:ios:b0f53252b619b74b9cdd68',
    messagingSenderId: '828363531961',
    projectId: 'mpl-lab-922a1',
    storageBucket: 'mpl-lab-922a1.firebasestorage.app',
    iosBundleId: 'com.example.mplLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8mIx4sxko-5xT32KJUq84BtUHdi-k6s',
    appId: '1:828363531961:ios:b0f53252b619b74b9cdd68',
    messagingSenderId: '828363531961',
    projectId: 'mpl-lab-922a1',
    storageBucket: 'mpl-lab-922a1.firebasestorage.app',
    iosBundleId: 'com.example.mplLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6_mkoUS6lCtdghA0BoPOVxywcJv0H_tA',
    appId: '1:828363531961:web:c9872763473eb7d59cdd68',
    messagingSenderId: '828363531961',
    projectId: 'mpl-lab-922a1',
    authDomain: 'mpl-lab-922a1.firebaseapp.com',
    storageBucket: 'mpl-lab-922a1.firebasestorage.app',
    measurementId: 'G-7X4RWK4BRN',
  );

}